"""Update Candidate model: add specialty field and make id_document required

Revision ID: 1d2205777fc0
Revises: 2442ad8a1896
Create Date: 2025-10-11 17:11:27.791387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2205777fc0'
down_revision = '2442ad8a1896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=255), nullable=True))
        batch_op.alter_column('id_document_filepath',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id_document_filepath',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
