"""Add experience, education, skills fields to Candidate

Revision ID: 2442ad8a1896
Revises: 6334828faaa4
Create Date: 2025-09-23 10:22:52.092786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2442ad8a1896'
down_revision = '6334828faaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('education')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
